FINISH
/CLEAR
/FILNAME,BeiPanJiang_Archbridge
/TITLE,Thermal_Analysis
/PREP7
/NERR,,99999999


!-------------------START-----------------------!
!~~~~~~~~~~~~~读入TAX数组（综合大气温度以及综合换热系数）~~~~~~~~~~~~~~~~!
*DIM,TAX,ARRAY,14,6,,TIME,BUWEI
!*VREAD,TAX(1,1),E:/TAX_BPJ/TAX_BPJ,TXT,,JIK,6,14,,1
!(F6.3,5F8.3)
/INPUT,E:/TAX_BPJ/READ_TAX,TXT!包含了上面的两条语句，在GUI中必须用这种方式读入array
HT=TAX(1,2)    !顶板综合换热系数
HB=TAX(1,3)    !底板综合换热系数
HWD=TAX(1,4)    !东侧腹板综合换热系数，W/(㎡*K)
HWX=TAX(1,5)    !西侧腹板综合换热系数
HI=TAX(1,6)    !内部综合换热系数
*STATUS,TAX
!--------------------END-------------------------!



!~~~~~~~~~~~~~定义MAT,ETYPE及参数~~~~~~~~~~~~~~~~!
ET,1,BEAM189
ET,2,SHELL131
KEYOPT,2,3,1
KEYOPT,2,4,10
!~~~~~~~~~~~~~钢材
MP,EX,1,2.1E11
MP,PRXY,1,0.3
MP,DENS,1,7850
!~~~~~~~~~~~~~C40（墩）、C55（梁）钢筋混凝土
MP,EX,2,3.4E10
MP,PRXY,2,0.25
MP,DENS,2,2550
!~~~~~~~~~~~~~C60钢筋混凝土
MP,EX,3,3.6E10
MP,PRXY,3,0.25
MP,DENS,3,2550
MP,KXX,3,3.4    !KXX-热传导系数，国际制单位是W/（m·K）
MP,KYY,3,3.4
MP,KZZ,3,3.4
MP,C,3,950    !比热容，J/(kg·K）

R1=0.5
R2=0.55
R3=0.6 
R4=0.65
R5=0.7 
R6=0.75
R7=0.8 
R8=0.9 
R9=1.1 

T1=R1/10
T2=R2/10
T3=R3/10
T4=R4/10
T5=R5/10
T6=R6/10
T7=R7/10
T8=R8/10
T9=R9/10

!~~~~~~~~~~~~~C80钢筋混凝土
MP,EX,4,3.8E10
MP,PRXY,4,0.25
MP,DENS,4,2550
!~~~~~~~~~~~~~杆件分段数
N=3
MA=6
!----------------------END--------------------------!



!-------------------START-----------------------!
!~~~~~~~~~~~~~读入定义混凝土板的点号~~~~~~~~~~~~~~~~!
/INPUT,1-5KP1,mac
/INPUT,6-20KP1,mac
/INPUT,1-5KPB1,mac
/INPUT,6-7KPB1,mac
/INPUT,8-20KPB1,mac     
!----------------------END--------------------------!


!~~~~~~~~~~~~~~~~~~定义壳截面~~~~~~~~~~~~~~~~~~~~!
!----------------------START-------------------------!
!~~~~~~~~~~~~~~~~~~定义51~59号壳截面，对应R1~R9
!------定义51~59号壳截面
*DO,I,1,9,1

SECTYPE,50+I,SHELL
*DO,Z,1,10,1
SECDATA,T%I%,3,,3,LAYER%Z%!---------------输入第一层的厚度、材料号、层角、积分点数及层的名称
*ENDDO
SECOFFSET,MID
SECCONTROLS,0,0,0,0,1,1,1

*ENDDO
!-------------------------END-----------------------------!



!----------------------------START-----------------------------!
!~~~~~~~~~~~~~建立小里程左侧四分之一模型~~~~~~~~~~~~~~~~~~~~!
!~~~~~~~~~~~~~~~~~~建立1/4外包混凝土~~~~~~~~~~~~~~~~~~~~!
/INPUT,HNTB1-5-1,MAC
/INPUT,HNTB6-7-1,MAC
/INPUT,HNTB8-20-1,MAC
/INPUT,HLDB1,MAC


!~~~~~~~~~~~划分所有面单元
ASEL,S,TYPE,,2
AMESH,ALL
!~~~~~~~~~~~对称四分之一实体结构形成全桥结构~~~~~~~~~~~~~!
/INPUT,SYMM,MAC
CSDELE,ALL
!~~~~~~~~~~~融合所有重合节点
ALLSEL
NUMMRG,NODE


!~~~~~~~~~~~~~--------求解模块-----------~~~~~~~~~~~~~~~~~~~~!
!-------------------------START-----------------------------!
FINI
/SOLU
ANTYPE,TRANS
TRNOPT,FULL    !瞬态热分析唯一可以使用选项
TIMINT,ON    !瞬态热分析和稳态热分析唯一区别
TUNIF,29.5    !根据8点所有测点实测温度平均得出
OUTRES,ALL

!-----------------循环加载----------------------!
!------------------START--------------------!
!*DO,I,1,7,1
*DO,M,2,14,1
!M=2
TIME,3600*(M-1)
NSUBST,1,100,1
AUTOTS,ON
EQSLV,JCG
KBC,0    !采用渐进荷载


!-----------------施加对流荷载----------------------!
!------------------START--------------------!
!-------------给顶面施加对流荷载
ASEL,NONE

*DO,I,1,4,1
*DO,Z,1,20,1
ASEL,A,,,SB%I%%Z%
ASEL,A,,,ZSB%I%%Z%
*ENDDO
ASEL,A,,,HLDSB%I%
ASEL,A,,,HLDZSB%I%
*ENDDO

SFA,ALL,1,CONV,HT,TAX(M,2)
!-------------给底面施加对流荷载
ASEL,NONE

*DO,I,1,4,1
*DO,Z,1,20,1
ASEL,A,,,XB%I%%Z%
ASEL,A,,,ZXB%I%%Z%
*ENDDO
ASEL,A,,,HLDXB%I%
ASEL,A,,,HLDZXB%I%
*ENDDO

SFA,ALL,2,CONV,HB,TAX(M,3)
!-------------给WEBD（右侧面）施加对流荷载
ASEL,NONE

*DO,I,2,4,2
*DO,Z,1,20,1
ASEL,A,,,WB%I%%Z%
*ENDDO
ASEL,A,,,HLDWB%I%
*ENDDO

SFA,ALL,2,CONV,HWD,TAX(M,4)
!-------------给WEBX（左侧面）施加对流荷载
ASEL,NONE

*DO,I,1,3,2
*DO,Z,1,20,1
ASEL,A,,,WB%I%%Z%
*ENDDO
ASEL,A,,,HLDWB%I%
*ENDDO

SFA,ALL,2,CONV,HWX,TAX(M,5)
!-------------给箱子内部施加对流荷载
!-------------第一部分
ASEL,NONE

*DO,I,1,4,1
*DO,Z,1,20,1
ASEL,A,,,WB%I%%Z%
ASEL,A,,,NB%I%%Z%
ASEL,A,,,XB%I%%Z%
ASEL,A,,,ZXB%I%%Z%
*ENDDO
ASEL,A,,,HLDWB%I%
ASEL,A,,,HLDNB%I%
ASEL,A,,,HLDXB%I%
ASEL,A,,,HLDZXB%I%
*ENDDO

SFA,ALL,1,CONV,HI,TAX(M,6)
!-------------第二部分
ASEL,NONE

*DO,I,1,4,1
*DO,Z,1,20,1
ASEL,A,,,NB%I%%Z%
ASEL,A,,,SB%I%%Z%
ASEL,A,,,ZSB%I%%Z%
*ENDDO
ASEL,A,,,HLDNB%I%
ASEL,A,,,HLDSB%I%
ASEL,A,,,HLDZSB%I%
*ENDDO

SFA,ALL,2,CONV,HI,TAX(M,6)
!-----------------END---------------------!

ALLSEL,ALL
SOLVE
*ENDDO
!*ENDDO
!------------------------END---------------------------!


!!~~~~~~~~~~~~~~~~~~后处理模块~~~~~~~~~~~~~~~~~~~~!
!--------------------START-----------------------!
/POST1
SET,LAST
PLNSOL,TEMP


